# 2023-02-02

name: checkov-01
# on: [push]
on:
  push:
    branches:
      - main
jobs:
  Checkov-Terraform-Scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform-in-action/chapter1
          framework: terraform
